# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20170428_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='university.Profile'),
            preserve_default=False,
        ),
    ]
