# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20170428_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_sem',
            field=models.IntegerField(max_length=8),
        ),
    ]
