# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_student_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[(b'S', b'Student'), (b'F', b'Faculty Member')], default='S', max_length=1),
            preserve_default=False,
        ),
    ]
