# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Event starts at')),
                ('end_datetime', models.DateTimeField(verbose_name='Event ends at')),
                ('repeat', models.CharField(choices=[('Y', 'Yearly'), ('y', 'Biyearly'), ('M', 'Monthly'), ('W', 'Weekly'), ('w', 'Biweekly'), ('D', 'Daily')], max_length=1, null=True)),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('final_endtime', models.DateTimeField(blank=True, null=True)),
                ('place', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepeatRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
